spring.application.name=cardapp
# 1. \uC11C\uBC84 \uD3EC\uD2B8 \uBC0F \uACBD\uB85C \uC124\uC815
# \uC678\uBD80\uC5D0\uC11C \uC811\uC18D\uD560 \uB54C http://\uC8FC\uC18C/card \uB85C \uC811\uC18D\uD558\uAE30 \uC704\uD55C \uC124\uC815\uC785\uB2C8\uB2E4.
server.port=8080
server.servlet.context-path=/card
# Session timeout. If a duration suffix is not specified, seconds will be used.
server.servlet.session.timeout=3600
# . \uD0C0\uC784\uB9AC\uD504(Thymeleaf) \uC124\uC815
# \uAC1C\uBC1C \uC911\uC5D0 HTML\uC744 \uC218\uC815\uD558\uACE0 \uBC14\uB85C \uD655\uC778\uD558\uAE30 \uC704\uD574 \uCE90\uC2DC\uB97C \uB055\uB2C8\uB2E4.
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
#\uB85C\uADF8 - logback\uC0AC\uC6A9\uD558\uAE30 \uC704\uD574 \uC8FC\uC11D \uCC98\uB9AC
#logging.level=debug
#logging.level.AIcard.cardapp=debug
#\uC5D0\uB7EC\uD398\uC774\uC9C0 \uACBD\uB85C \uC9C0\uC815
server.error.path=/error
# 404 \uC5D0\uB7EC\uB97C \uC2A4\uD504\uB9C1 \uB0B4\uBD80 \uC608\uC678\uB85C \uB358\uC9C0\uAC8C \uD568 (\uADF8\uB798\uC57C \uCEE8\uD2B8\uB864\uB7EC\uAC00 \uC7A1\uC74C)
spring.mvc.throw-exception-if-no-handler-found=true
# \uC815\uC801 \uB9AC\uC18C\uC2A4 \uD578\uB4E4\uB9C1 \uC2DC \uC5D0\uB7EC \uD398\uC774\uC9C0\uB85C \uB118\uC5B4\uAC00\uB3C4\uB85D \uC124\uC815
spring.web.resources.add-mappings=true
# \uB85C\uCEEC \uC0AC\uC6A9\uC2DC local \uC2E4 \uC11C\uBC84\uC5D0\uC11C\uB294 prod
spring.profiles.active=local
openai.api.key=${OPENAI_API_KEY:}
openai.model=gpt-5.4-mini
gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
google.client-id=893320613116-b1d36l01tvd7gqqt3dkaj22qapb45aua.apps.googleusercontent.com
google.client-secret=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
