# [\uC11C\uBC84 DB \uC5F0\uACB0 - \uB3C4\uCEE4 \uC11C\uBE44\uC2A4\uBA85 'db' \uC0AC\uC6A9]
spring.datasource.url=jdbc:mariadb://db:3306/myapp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=71603386
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# \uC11C\uBC84\uC5D0\uC11C\uB294 \uB370\uC774\uD130 \uBCF4\uD638\uB97C \uC704\uD574 \uAD6C\uC870 \uBCC0\uACBD\uC744 \uAE08\uC9C0\uD569\uB2C8\uB2E4.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
# \uC11C\uBC84 \uC131\uB2A5\uC744 \uC704\uD574 \uD0C0\uC784\uB9AC\uD504 \uCE90\uC2DC \uD65C\uC131\uD654
spring.thymeleaf.cache=true

app.generated-card-dir=/app/generated-cards
