spring.application.name=cardapp

# 1. \uc11c\ubc84 \ud3ec\ud2b8 \ubc0f \uacbd\ub85c \uc124\uc815
# \uc678\ubd80\uc5d0\uc11c \uc811\uc18d\ud560 \ub54c http://\uc8fc\uc18c/card \ub85c \uc811\uc18d\ud558\uae30 \uc704\ud55c \uc124\uc815\uc785\ub2c8\ub2e4.
server.port=8080
server.servlet.context-path=/card
# Session timeout. If a duration suffix is not specified, seconds will be used.
server.servlet.session.timeout=3600

# 2. \ub370\uc774\ud130\ubca0\uc774\uc2a4 \uc5f0\uacb0 (\uc911\uc694: localhost \ub300\uc2e0 \ub3c4\ucee4 \uc11c\ube44\uc2a4\uba85 'db' \uc0ac\uc6a9)
# myapp\uc740 docker-compose\uc5d0\uc11c \uc124\uc815\ud55c MYSQL_DATABASE \uc774\ub984\uc785\ub2c8\ub2e4.
#spring.datasource.url=jdbc:mysql://db:3306/myapp?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=71603386
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 로컬 테스트용 메모리 데이터베이스임 실제 배포시에 위에거 주석 해제 하고 이건 주석처리하셈
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 3. JPA/Hibernate \uc124\uc815
# \uc11c\ubc84 \uc2e4\ud589 \uc2dc \uc5d4\ud2f0\ud2f0(Entity) \ud074\ub798\uc2a4\ub97c \ubc14\ud0d5\uc73c\ub85c \ud14c\uc774\ube14\uc744 \uc790\ub3d9\uc73c\ub85c \uc0dd\uc131/\uc5c5\ub370\uc774\ud2b8\ud569\ub2c8\ub2e4.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 4. \ud0c0\uc784\ub9ac\ud504(Thymeleaf) \uc124\uc815
# \uac1c\ubc1c \uc911\uc5d0 HTML\uc744 \uc218\uc815\ud558\uace0 \ubc14\ub85c \ud655\uc778\ud558\uae30 \uc704\ud574 \uce90\uc2dc\ub97c \ub055\ub2c8\ub2e4.
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

logging.level=debug
logging.level.AIcard.cardapp=debug